CREATE TABLE happiness_2021 (
Country_name text primary key,
Regional_indicator text,
	Ladder_score float,
	Standard_error float,
	upperwhisker float,
	lowerwhisker float,
	logged_GDP_per_capita float,
	Social_support float,
	Healthy_life_expectancy float,
	Freedom_to_make_life_choices float,
	Generosity float,
	Perceptions_of_corruption float,
	Ladder_score_in_Dystopia float,
	Explained_by_Log_GDP_per_capita float,
	Explained_by_Social_support float,
	Explained_by_Healthy_life_expectancy float,
	Explained_by_Freedom_to_make_life_choices float,
	Explained_by_Generosity float,
	Explained_by_Perceptions_of_corruption float,
	Dystopia_residual float);
	
CREATE TABLE happiness_2020 (
Country_name text primary key,
Regional_indicator text,
	Ladder_score float,
	Standard_error float,
	upperwhisker float,
	lowerwhisker float,
	logged_GDP_per_capita float,
	Social_support float,
	Healthy_life_expectancy float,
	Freedom_to_make_life_choices float,
	Generosity float,
	Perceptions_of_corruption float,
	Ladder_score_in_Dystopia float,
	Explained_by_Log_GDP_per_capita float,
	Explained_by_Social_support float,
	Explained_by_Healthy_life_expectancy float,
	Explained_by_Freedom_to_make_life_choices float,
	Explained_by_Generosity float,
	Explained_by_Perceptions_of_corruption float,
	Dystopia_residual float);

CREATE TABLE costofliving(
Rank INT,
Country TEXT,
Cost_of_Living_Index FLOAT,
Rent_Index FLOAT,
Cost_of_Living_Plus_Rent_Index FLOAT,
Groceries_Index FLOAT,
Restaurant_Price_Index FLOAT,
Local_Purchasing_Power_Index FLOAT);